### PR TITLE
initial commit for voice-recorder feature made use of code from https://github.com/MohammadAG/Android-SoundRecorder

### PR DESCRIPTION
**Pull request by abdlquadri**
…ecorder. Kindly review.

### CODE REVIEW

**Comment by calistus** [comment]
Kindly change the commit message. The word dub sounds more like plagiarism :) meanwhile it does apply here since your source of clone is open source

**Comment by abdlquadri** [comment]
I deliberately wrote that way to pay tribute to the source.

**Comment by abdlquadri** [comment]
But If you think it should be changed, I will. Can you suggest a better message.

**Comment by calistus** [comment]
I think this will be better

"Initial commit for Records. Made use of the code at https://github.com/MohammadAG/Android-SoundRecorder "

**Pull request merged**
